package co.edu.utp.isc.pro4.exammaker.view;

import co.edu.utp.isc.pro4.exammaker.controller.ExamController;

/**
 *
 * @author Esteban
 */
public class CreateExamPnl extends javax.swing.JPanel implements FrameControl {

    /**
     * Creates new form ProfessorJPanel
     */
    public CreateExamPnl() {
        initComponents();
        this.addQuestionPnl1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtExamName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaExamDescription = new javax.swing.JTextArea();
        btnCrear = new javax.swing.JButton();
        jPnlQuestions = new javax.swing.JPanel();
        jPnlEmpty = new javax.swing.JPanel();
        addQuestionPnl1 = new co.edu.utp.isc.pro4.exammaker.view.AddQuestionPnl();
        jLabel3 = new javax.swing.JLabel();
        txtMaxGrade = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear Examen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel1.setText("Nombre del examen:");

        jLabel2.setText("Descripción:");

        txtExamName.setText("TEST PARCIAL");
        txtExamName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExamNameActionPerformed(evt);
            }
        });

        txaExamDescription.setColumns(20);
        txaExamDescription.setRows(5);
        txaExamDescription.setText("ESTO ES UN TEST");
        jScrollPane1.setViewportView(txaExamDescription);

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jPnlQuestions.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPnlEmptyLayout = new javax.swing.GroupLayout(jPnlEmpty);
        jPnlEmpty.setLayout(jPnlEmptyLayout);
        jPnlEmptyLayout.setHorizontalGroup(
            jPnlEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        jPnlEmptyLayout.setVerticalGroup(
            jPnlEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        jPnlQuestions.add(jPnlEmpty, "empty");
        jPnlQuestions.add(addQuestionPnl1, "questions");

        jLabel3.setText("Nota máxima:");

        txtMaxGrade.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCrear))
                            .addComponent(txtExamName)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtExamName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear)
                    .addComponent(jLabel3)
                    .addComponent(txtMaxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jPnlQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtExamNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExamNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExamNameActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String name = txtExamName.getText().trim();
        String description = txaExamDescription.getText().trim();
        double maxGrade = Double.parseDouble(txtMaxGrade.getText().trim());
        
        ExamController.getInstance().createExam(name, description, maxGrade);
        
        switchCard("questions");
    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private co.edu.utp.isc.pro4.exammaker.view.AddQuestionPnl addQuestionPnl1;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPnlEmpty;
    private javax.swing.JPanel jPnlQuestions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaExamDescription;
    private javax.swing.JTextField txtExamName;
    private javax.swing.JTextField txtMaxGrade;
    // End of variables declaration//GEN-END:variables
    
    
    @Override
    public void switchCard(String card) {
        if (card.equals("questions")) {
            this.jPnlEmpty.setVisible(false);
            this.addQuestionPnl1.setVisible(true);
        }
    }
}
