package co.edu.utp.isc.pro4.exammaker.view;

import co.edu.utp.isc.pro4.exammaker.controller.GraderController;
import co.edu.utp.isc.pro4.exammaker.controller.SolverController;

/**
 *
 * @author Esteban
 */
public class ExamMakerFrm extends javax.swing.JFrame implements FrameControl {

    /**
     * Creates new form ExamMakerJFrame
     */
    public ExamMakerFrm() {
        initComponents();
        startApp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnProfesor = new javax.swing.JButton();
        btnEstudiante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPnlProfessor = new javax.swing.JPanel();
        btnCrearExamen = new javax.swing.JButton();
        btnCalificarExamen = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPnlCreateExam = new javax.swing.JPanel();
        createExamPnl1 = new co.edu.utp.isc.pro4.exammaker.view.CreateExamPnl();
        jPnlStudent = new javax.swing.JPanel();
        solveExamPnl1 = new co.edu.utp.isc.pro4.exammaker.view.SolveExamPnl();
        jPnlGradeExam = new javax.swing.JPanel();
        gradeExamPnl1 = new co.edu.utp.isc.pro4.exammaker.view.GradeExamPnl();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exam Maker");
        getContentPane().setLayout(new java.awt.CardLayout());

        jPnlLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPnlLogin.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a Exam Maker");

        btnProfesor.setText("Profesor");
        btnProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesorActionPerformed(evt);
            }
        });

        btnEstudiante.setText("Estudiante");
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Entrar como:");

        javax.swing.GroupLayout jPnlLoginLayout = new javax.swing.GroupLayout(jPnlLogin);
        jPnlLogin.setLayout(jPnlLoginLayout);
        jPnlLoginLayout.setHorizontalGroup(
            jPnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlLoginLayout.createSequentialGroup()
                .addGroup(jPnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlLoginLayout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(jPnlLoginLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel2)))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(jPnlLoginLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        jPnlLoginLayout.setVerticalGroup(
            jPnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlLoginLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(jPnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlLoginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(122, 122, 122))
                    .addGroup(jPnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(408, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlLogin, "login");

        jPnlProfessor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profesor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        btnCrearExamen.setText("Crear Examen");
        btnCrearExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearExamenActionPerformed(evt);
            }
        });

        btnCalificarExamen.setText("Calificar Examen");
        btnCalificarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarExamenActionPerformed(evt);
            }
        });

        jLabel3.setText("Elija una opción");

        javax.swing.GroupLayout jPnlProfessorLayout = new javax.swing.GroupLayout(jPnlProfessor);
        jPnlProfessor.setLayout(jPnlProfessorLayout);
        jPnlProfessorLayout.setHorizontalGroup(
            jPnlProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlProfessorLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(314, 314, 314))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlProfessorLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnCrearExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalificarExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPnlProfessorLayout.setVerticalGroup(
            jPnlProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlProfessorLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel3)
                .addGap(158, 158, 158)
                .addGroup(jPnlProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalificarExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(424, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlProfessor, "professor");

        javax.swing.GroupLayout jPnlCreateExamLayout = new javax.swing.GroupLayout(jPnlCreateExam);
        jPnlCreateExam.setLayout(jPnlCreateExamLayout);
        jPnlCreateExamLayout.setHorizontalGroup(
            jPnlCreateExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCreateExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createExamPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPnlCreateExamLayout.setVerticalGroup(
            jPnlCreateExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlCreateExamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createExamPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPnlCreateExam, "create");

        javax.swing.GroupLayout jPnlStudentLayout = new javax.swing.GroupLayout(jPnlStudent);
        jPnlStudent.setLayout(jPnlStudentLayout);
        jPnlStudentLayout.setHorizontalGroup(
            jPnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(solveExamPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlStudentLayout.setVerticalGroup(
            jPnlStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(solveExamPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlStudent, "student");

        javax.swing.GroupLayout jPnlGradeExamLayout = new javax.swing.GroupLayout(jPnlGradeExam);
        jPnlGradeExam.setLayout(jPnlGradeExamLayout);
        jPnlGradeExamLayout.setHorizontalGroup(
            jPnlGradeExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlGradeExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradeExamPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlGradeExamLayout.setVerticalGroup(
            jPnlGradeExamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlGradeExamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gradeExamPnl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPnlGradeExam, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesorActionPerformed
        switchCard("professor");
    }//GEN-LAST:event_btnProfesorActionPerformed

    private void btnCrearExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearExamenActionPerformed
        switchCard("create");
    }//GEN-LAST:event_btnCrearExamenActionPerformed

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        SolverController.getInstance().loadExam();
        switchCard("student");
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void btnCalificarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificarExamenActionPerformed
        GraderController.getInstance().loadSolvedExam();
        GraderController.getInstance().checkAnswers();
        switchCard("grade");
        gradeExamPnl1.getAnswers();
    }//GEN-LAST:event_btnCalificarExamenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamMakerFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamMakerFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamMakerFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamMakerFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamMakerFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificarExamen;
    private javax.swing.JButton btnCrearExamen;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JButton btnProfesor;
    private co.edu.utp.isc.pro4.exammaker.view.CreateExamPnl createExamPnl1;
    private co.edu.utp.isc.pro4.exammaker.view.GradeExamPnl gradeExamPnl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPnlCreateExam;
    private javax.swing.JPanel jPnlGradeExam;
    private javax.swing.JPanel jPnlLogin;
    private javax.swing.JPanel jPnlProfessor;
    private javax.swing.JPanel jPnlStudent;
    private co.edu.utp.isc.pro4.exammaker.view.SolveExamPnl solveExamPnl1;
    // End of variables declaration//GEN-END:variables

    private void startApp() {
        setLocationRelativeTo(null);
    }
    
    @Override
    public void switchCard(String card) {
        switch (card) {
            case "professor":
                jPnlLogin.setVisible(false);
                jPnlProfessor.setVisible(true);
                break;
            case "create":
                jPnlProfessor.setVisible(false);
                jPnlCreateExam.setVisible(true);
                break;
            case "student":
                jPnlLogin.setVisible(false);
                jPnlStudent.setVisible(true);
                break;
            case "grade":
                jPnlLogin.setVisible(false);
                jPnlProfessor.setVisible(false);
                jPnlGradeExam.setVisible(true);
            default:
                break;
        }
    }
    
}
