package co.edu.utp.isc.pro4.exammaker.view;

import co.edu.utp.isc.pro4.exammaker.controller.SolverController;
import co.edu.utp.isc.pro4.exammaker.model.Question;
import co.edu.utp.isc.pro4.exammaker.model.QuestionMultipleAnswer;
import co.edu.utp.isc.pro4.exammaker.model.QuestionOpenAnswer;
import co.edu.utp.isc.pro4.exammaker.model.QuestionType;
import co.edu.utp.isc.pro4.exammaker.model.QuestionUniqueAnswer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Esteban
 */
public class SolveExamPnl extends javax.swing.JPanel implements FrameControl {

    /**
     * Creates new form SolveExamPnl
     */
    public SolveExamPnl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPnlQuestionType = new javax.swing.JPanel();
        jPnlEmpty4 = new javax.swing.JPanel();
        jPnlOpenQuestion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaStatement = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaAnswer = new javax.swing.JTextArea();
        jPnlUniqueAnswer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaStatement1 = new javax.swing.JTextArea();
        radOptionA = new javax.swing.JRadioButton();
        radOptionB = new javax.swing.JRadioButton();
        radOptionC = new javax.swing.JRadioButton();
        radOptionD = new javax.swing.JRadioButton();
        jPnlMultipleAnswer = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaStatement2 = new javax.swing.JTextArea();
        chkOptionA = new javax.swing.JCheckBox();
        chkOptionB = new javax.swing.JCheckBox();
        chkOptionC = new javax.swing.JCheckBox();
        chkOptionD = new javax.swing.JCheckBox();
        btnSiguientePregunta = new javax.swing.JButton();
        btnEmpezarExamen = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estudiante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        setPreferredSize(new java.awt.Dimension(740, 763));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Resolver Examen"));
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 550));

        jPnlQuestionType.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPnlEmpty4Layout = new javax.swing.GroupLayout(jPnlEmpty4);
        jPnlEmpty4.setLayout(jPnlEmpty4Layout);
        jPnlEmpty4Layout.setHorizontalGroup(
            jPnlEmpty4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        jPnlEmpty4Layout.setVerticalGroup(
            jPnlEmpty4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPnlQuestionType.add(jPnlEmpty4, "empty4");

        jLabel1.setText("Responda la siguiente pregunta en el área de texto");

        jLabel2.setText("PREGUNTA ABIERTA");

        jLabel3.setText("Enunciado:");

        jLabel4.setText("Respuesta:");

        txaStatement.setEditable(false);
        txaStatement.setColumns(20);
        txaStatement.setLineWrap(true);
        txaStatement.setRows(5);
        txaStatement.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaStatement);

        txaAnswer.setColumns(20);
        txaAnswer.setLineWrap(true);
        txaAnswer.setRows(5);
        txaAnswer.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txaAnswer);

        javax.swing.GroupLayout jPnlOpenQuestionLayout = new javax.swing.GroupLayout(jPnlOpenQuestion);
        jPnlOpenQuestion.setLayout(jPnlOpenQuestionLayout);
        jPnlOpenQuestionLayout.setHorizontalGroup(
            jPnlOpenQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlOpenQuestionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPnlOpenQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addGroup(jPnlOpenQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPnlOpenQuestionLayout.setVerticalGroup(
            jPnlOpenQuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlOpenQuestionLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPnlQuestionType.add(jPnlOpenQuestion, "open");

        jLabel5.setText("PREGUNTA OPCIÓN MÚLTIPLE, ÚNICA RESPUESTA");

        jLabel6.setText("Responda la siguiente pregunta seleccionando una única opción");

        jLabel7.setText("Enunciado:");

        txaStatement1.setEditable(false);
        txaStatement1.setColumns(20);
        txaStatement1.setLineWrap(true);
        txaStatement1.setRows(5);
        txaStatement1.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txaStatement1);

        btnGroup.add(radOptionA);

        btnGroup.add(radOptionB);

        btnGroup.add(radOptionC);

        btnGroup.add(radOptionD);

        javax.swing.GroupLayout jPnlUniqueAnswerLayout = new javax.swing.GroupLayout(jPnlUniqueAnswer);
        jPnlUniqueAnswer.setLayout(jPnlUniqueAnswerLayout);
        jPnlUniqueAnswerLayout.setHorizontalGroup(
            jPnlUniqueAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlUniqueAnswerLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPnlUniqueAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radOptionD)
                    .addComponent(radOptionC)
                    .addComponent(radOptionB)
                    .addComponent(radOptionA)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlUniqueAnswerLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel5)))
                .addGap(31, 31, 31))
        );
        jPnlUniqueAnswerLayout.setVerticalGroup(
            jPnlUniqueAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUniqueAnswerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(radOptionA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radOptionB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radOptionC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radOptionD)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPnlQuestionType.add(jPnlUniqueAnswer, "unique");

        jLabel8.setText("PREGUNTA OPCIÓN MÚLTIPLE, MÚLTIPLE RESPUESTA");

        jLabel9.setText("Responda la siguiente pregunta seleccionando las opciones correctas");

        jLabel10.setText("Enunciado:");

        txaStatement2.setEditable(false);
        txaStatement2.setColumns(20);
        txaStatement2.setLineWrap(true);
        txaStatement2.setRows(5);
        txaStatement2.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txaStatement2);

        javax.swing.GroupLayout jPnlMultipleAnswerLayout = new javax.swing.GroupLayout(jPnlMultipleAnswer);
        jPnlMultipleAnswer.setLayout(jPnlMultipleAnswerLayout);
        jPnlMultipleAnswerLayout.setHorizontalGroup(
            jPnlMultipleAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlMultipleAnswerLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPnlMultipleAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkOptionD)
                    .addComponent(chkOptionC)
                    .addComponent(chkOptionB)
                    .addComponent(chkOptionA)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlMultipleAnswerLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel8)))
                .addGap(30, 30, 30))
        );
        jPnlMultipleAnswerLayout.setVerticalGroup(
            jPnlMultipleAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMultipleAnswerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(chkOptionA)
                .addGap(18, 18, 18)
                .addComponent(chkOptionB)
                .addGap(18, 18, 18)
                .addComponent(chkOptionC)
                .addGap(18, 18, 18)
                .addComponent(chkOptionD)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPnlQuestionType.add(jPnlMultipleAnswer, "multiple");

        btnSiguientePregunta.setText("Siguiente Pregunta");
        btnSiguientePregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguientePreguntaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlQuestionType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSiguientePregunta)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnlQuestionType, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSiguientePregunta)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnEmpezarExamen.setText("Empezar Examen");
        btnEmpezarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarExamenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEmpezarExamen)
                        .addGap(287, 287, 287))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnEmpezarExamen)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpezarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarExamenActionPerformed
        this.questions = SolverController.getInstance().getExam().getQuestions();
        if (!questions.isEmpty()) {
            updateQuestion();
            showQuestion();
        } else {
            System.out.println("lista vacia");
        }
    }//GEN-LAST:event_btnEmpezarExamenActionPerformed

    private void btnSiguientePreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguientePreguntaActionPerformed
        switch (type) {
            case OPEN:
                ((QuestionOpenAnswer) currentQuestion).setAnswer(txaAnswer.getText().trim());
                break;
            case UNIQUE:
                int num = -1;
                if (radOptionA.isSelected()) {
                    num = 0;
                } else if (radOptionB.isSelected()) {
                    num = 1;
                } else if (radOptionC.isSelected()) {
                    num = 2;
                } else if (radOptionD.isSelected()) {
                    num = 3;
                }
                ((QuestionUniqueAnswer) currentQuestion).setChosenOptionIndex(num);
                break;
            case MULTIPLE:
                List<Integer> nums = new ArrayList();
                if (chkOptionA.isSelected()) {
                    nums.add(0);
                }
                if (chkOptionB.isSelected()) {
                    nums.add(1);
                }
                if (chkOptionC.isSelected()) {
                    nums.add(2);
                }
                if (chkOptionD.isSelected()) {
                    nums.add(3);
                }
                ((QuestionMultipleAnswer) currentQuestion).setChosenOptionsIndexes(nums);
                break;
        }
        updateQuestion();
    }//GEN-LAST:event_btnSiguientePreguntaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpezarExamen;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnSiguientePregunta;
    private javax.swing.JCheckBox chkOptionA;
    private javax.swing.JCheckBox chkOptionB;
    private javax.swing.JCheckBox chkOptionC;
    private javax.swing.JCheckBox chkOptionD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlEmpty4;
    private javax.swing.JPanel jPnlMultipleAnswer;
    private javax.swing.JPanel jPnlOpenQuestion;
    private javax.swing.JPanel jPnlQuestionType;
    private javax.swing.JPanel jPnlUniqueAnswer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton radOptionA;
    private javax.swing.JRadioButton radOptionB;
    private javax.swing.JRadioButton radOptionC;
    private javax.swing.JRadioButton radOptionD;
    private javax.swing.JTextArea txaAnswer;
    private javax.swing.JTextArea txaStatement;
    private javax.swing.JTextArea txaStatement1;
    private javax.swing.JTextArea txaStatement2;
    // End of variables declaration//GEN-END:variables
    private List<Question> questions;
    private int index = -1;
    private Question currentQuestion;
    private QuestionType type;
    
    private void updateQuestion() {
        index++;
        if (index >= questions.size()) {
            clean();
            JOptionPane.showMessageDialog(this, "No hay más preguntas", "Examen terminado", JOptionPane.INFORMATION_MESSAGE);
            SolverController.getInstance().saveSolvedExam();
            this.setVisible(false);
        } else {
            currentQuestion = questions.get(index);
            type = currentQuestion.getType();
            showQuestion();
        }
    }
    
    public void clean() {
        txaStatement.setText("");
        txaAnswer.setText("");
        txaStatement1.setText("");
        btnGroup.clearSelection();
        chkOptionA.setSelected(false);
        chkOptionB.setSelected(false);
        chkOptionC.setSelected(false);
        chkOptionD.setSelected(false);
    }
    
    public void showQuestion() {
        clean();
        if (currentQuestion != null) {
            switch(type) {
                case OPEN:
                    txaStatement.setText(currentQuestion.getStatement());
                    switchCard("open");
                    break;
                case UNIQUE:
                    txaStatement1.setText(currentQuestion.getStatement());
                    radOptionA.setText(((QuestionUniqueAnswer) currentQuestion).getOptions().get(0));
                    radOptionB.setText(((QuestionUniqueAnswer) currentQuestion).getOptions().get(1));
                    radOptionC.setText(((QuestionUniqueAnswer) currentQuestion).getOptions().get(2));
                    radOptionD.setText(((QuestionUniqueAnswer) currentQuestion).getOptions().get(3));
                    switchCard("unique");
                    break;
                case MULTIPLE:
                    txaStatement2.setText(currentQuestion.getStatement());
                    chkOptionA.setText(((QuestionMultipleAnswer) currentQuestion).getOptions().get(0));
                    chkOptionB.setText(((QuestionMultipleAnswer) currentQuestion).getOptions().get(1));
                    chkOptionC.setText(((QuestionMultipleAnswer) currentQuestion).getOptions().get(2));
                    chkOptionD.setText(((QuestionMultipleAnswer) currentQuestion).getOptions().get(3));
                    switchCard("multiple");
                    break;
            }
        }
    }
    
    @Override
    public void switchCard(String card) {
        switch(card) {
            case "open":
                jPnlEmpty4.setVisible(false);
                jPnlUniqueAnswer.setVisible(false);
                jPnlMultipleAnswer.setVisible(false);
                jPnlOpenQuestion.setVisible(true);
                break;
            case "unique":
                jPnlEmpty4.setVisible(false);
                jPnlOpenQuestion.setVisible(false);
                jPnlMultipleAnswer.setVisible(false);
                jPnlUniqueAnswer.setVisible(true);
                break;
            case "multiple":
                jPnlEmpty4.setVisible(false);
                jPnlOpenQuestion.setVisible(false);
                jPnlUniqueAnswer.setVisible(false);
                jPnlMultipleAnswer.setVisible(true);
                break;
        }
    }
    
}
